"""

-- Mensagem no readme, não precisa = echo "# Dw-Zero" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/arexdevson/Dw-Zero.git
git push -u origin main

limpartela do terminal
clear

ambiente virtual = organizar versionamente do projeto = python -m venv .venv
.venv/Scripts/activate

pip install -r requirements.txt


AWS - POSTGRESSQL (PÕE CARTÃO)

ACESSO A CONTA FREE TIER DA AWS
VOU NA BARRA DE BUSCA POR RDS (RELATIONAL DATABASES)
DASHBOARD - PAINEL E CRIO UM BANCO DE DADOS POSTGRES
** MUITA ATENÇAO NO QUE ESCOLHER PRA NÃO PAGAR!!!

DAR NOME PRO BANCO
USUARIO
SENHA
PUBLICO OU PRIVADO?
E CRIO

RENDER (SEM CARTÃO)
ACESSO A CONTA FREE TIER RENDER


"""

print("First Step")