version: 2

sources:
  - name: PipelineCommodities
    schema: public
    tables:
      - name: commodities
        description: "Tabela que contém dados históricos de commodities"
        columns:
          - name: Date
            description: "Data da observação"
          - name: Close
            description: "Preço de fechamento da commodity"
          - name: simbolo
            description: "Símbolo da commodity"

      - name: mov_commodities
        description: "Tabela com as movimentações de commodities"
        columns:
          - name: date
            description: "Data da transação"
          - name: symbol 
            description: "Símbolo da commodity"
          - name: action 
            description: "Tipo de transação (buy/sell)"
          - name: quantity 
            description: "Quantidade transacionada"
